import { describe, expect, test } from '@jest/globals';
import request from 'supertest';
import {
  getLatitudeLogitude,
  getDistanceTwoPoint,
  makeGraph,
  getSmallerDistance,
  getGreaterDistance,
} from '../../services/ApiGeoapify';

describe('Test the services', () => {
  test('It should return address with lat and lon', async () => {
    const data = await getLatitudeLogitude({
      place_name: 'A',
      street: 'Av. Rio Branco',
      housenumber: '1',
      postcode: '20090003',
      city: 'Rio de Janeiro',
      neighborhood: 'Centro',
      state: 'RJ',
      country: 'Brasil',
      lat: '',
      lon: '',
    });
    expect(data).toEqual({
      place_name: 'A',
      street: 'Av. Rio Branco',
      housenumber: '1',
      postcode: '20090003',
      city: 'Rio de Janeiro',
      neighborhood: 'Centro',
      state: 'RJ',
      country: 'Brasil',
      lat: -22.89750765,
      lon: -43.18020490826943,
    });
  });
  test('It should return the distance between two points', async () => {
    const a = {
      place_name: 'A',
      street: 'Av. Rio Branco',
      housenumber: '1',
      postcode: '20090003',
      city: 'Rio de Janeiro',
      neighborhood: 'Centro',
      state: 'RJ',
      country: 'Brasil',
      lat: '-22.89750765',
      lon: '-43.18020490826943',
    };

    const b = {
      place_name: 'B',
      street: 'Rua Horacio Fontenele Magalhaes',
      housenumber: '329',
      postcode: '62300-000',
      city: 'Viçosa do Ceará',
      neighborhood: 'Northeast',
      state: 'CE',
      country: 'Brasil',
      lat: '-3.561473',
      lon: '-41.091586',
    };
    const data = await getDistanceTwoPoint(a, b);
    expect(data).toBe(2763882);
  });
  test('It should return the list distance between addresses', async () => {
    const addresses = [
      {
        place_name: 'A',
        street: 'Av. Rio Branco',
        housenumber: 1,
        postcode: '20090003',
        city: 'Rio de Janeiro',
        neighborhood: 'Centro',
        state: 'RJ',
        country: 'Brasil',
        lat: '-22.89750765',
        lon: '-43.18020490826943',
      },
      {
        place_name: 'B',
        street: 'Rua Horacio Fontenele Magalhaes',
        housenumber: 329,
        postcode: '62300-000',
        city: 'Viçosa do Ceará',
        neighborhood: 'Northeast',
        state: 'CE',
        country: 'Brasil',
        lat: '-3.561473',
        lon: '-41.091586',
      },
    ];
    const data = await makeGraph(addresses);
    expect(data).toEqual([
      {
        origin: {
          place_name: 'A',
          street: 'Av. Rio Branco',
          housenumber: 1,
          postcode: '20090003',
          city: 'Rio de Janeiro',
          neighborhood: 'Centro',
          state: 'RJ',
          country: 'Brasil',
          lat: -22.89750765,
          lon: -43.18020490826943,
        },
        destiny: {
          place_name: 'B',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 329,
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561473,
          lon: -41.091586,
        },
        distance: 2763.882,
      },
    ]);
  });
  test('It should return the smaller distance in list of distances', () => {
    const listDistance = [
      {
        origin: {
          place_name: 'A',
          street: 'Av. Rio Branco',
          housenumber: 1,
          postcode: '20090003',
          city: 'Rio de Janeiro',
          neighborhood: 'Centro',
          state: 'RJ',
          country: 'Brasil',
          lat: -22.89750765,
          lon: -43.18020490826943,
        },
        destiny: {
          place_name: 'B',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 329,
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561473,
          lon: -41.091586,
        },
        distance: 2763.882,
      },
      {
        origin: {
          place_name: 'A',
          street: 'Av. Rio Branco',
          housenumber: 1,
          postcode: '20090003',
          city: 'Rio de Janeiro',
          neighborhood: 'Centro',
          state: 'RJ',
          country: 'Brasil',
          lat: -22.89750765,
          lon: -43.18020490826943,
        },
        destiny: {
          place_name: 'C',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 2764.052,
      },
      {
        origin: {
          place_name: 'A',
          street: 'Av. Rio Branco',
          housenumber: 1,
          postcode: '20090003',
          city: 'Rio de Janeiro',
          neighborhood: 'Centro',
          state: 'RJ',
          country: 'Brasil',
          lat: -22.89750765,
          lon: -43.18020490826943,
        },
        destiny: {
          place_name: 'D',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 2764.052,
      },
      {
        origin: {
          place_name: 'B',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 329,
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561473,
          lon: -41.091586,
        },
        destiny: {
          place_name: 'C',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 0.169,
      },
      {
        origin: {
          place_name: 'B',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 329,
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561473,
          lon: -41.091586,
        },
        destiny: {
          place_name: 'D',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 0.169,
      },
      {
        origin: {
          place_name: 'C',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        destiny: {
          place_name: 'D',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 0,
      },
    ];

    const response = getSmallerDistance(listDistance);
    expect(response).toEqual({
      origin: {
        place_name: 'C',
        street: 'Rua Horacio Fontenele Magalhaes',
        housenumber: 'SN',
        postcode: '62300-000',
        city: 'Viçosa do Ceará',
        neighborhood: 'Northeast',
        state: 'CE',
        country: 'Brasil',
        lat: -3.561013,
        lon: -41.090133,
      },
      destiny: {
        place_name: 'D',
        street: 'Rua Horacio Fontenele Magalhaes',
        housenumber: 'SN',
        postcode: '62300-000',
        city: 'Viçosa do Ceará',
        neighborhood: 'Northeast',
        state: 'CE',
        country: 'Brasil',
        lat: -3.561013,
        lon: -41.090133,
      },
      distance: 0,
    });
  });

  test('It should return the greater distance distance in list of distances', () => {
    jest.setTimeout(50000);
    const listDistance = [
      {
        origin: {
          place_name: 'A',
          street: 'Av. Rio Branco',
          housenumber: 1,
          postcode: '20090003',
          city: 'Rio de Janeiro',
          neighborhood: 'Centro',
          state: 'RJ',
          country: 'Brasil',
          lat: -22.89750765,
          lon: -43.18020490826943,
        },
        destiny: {
          place_name: 'B',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 329,
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561473,
          lon: -41.091586,
        },
        distance: 2763.882,
      },
      {
        origin: {
          place_name: 'A',
          street: 'Av. Rio Branco',
          housenumber: 1,
          postcode: '20090003',
          city: 'Rio de Janeiro',
          neighborhood: 'Centro',
          state: 'RJ',
          country: 'Brasil',
          lat: -22.89750765,
          lon: -43.18020490826943,
        },
        destiny: {
          place_name: 'C',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 2764.052,
      },
      {
        origin: {
          place_name: 'A',
          street: 'Av. Rio Branco',
          housenumber: 1,
          postcode: '20090003',
          city: 'Rio de Janeiro',
          neighborhood: 'Centro',
          state: 'RJ',
          country: 'Brasil',
          lat: -22.89750765,
          lon: -43.18020490826943,
        },
        destiny: {
          place_name: 'D',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 2764.052,
      },
      {
        origin: {
          place_name: 'B',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 329,
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561473,
          lon: -41.091586,
        },
        destiny: {
          place_name: 'C',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 0.169,
      },
      {
        origin: {
          place_name: 'B',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 329,
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561473,
          lon: -41.091586,
        },
        destiny: {
          place_name: 'D',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 0.169,
      },
      {
        origin: {
          place_name: 'C',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        destiny: {
          place_name: 'D',
          street: 'Rua Horacio Fontenele Magalhaes',
          housenumber: 'SN',
          postcode: '62300-000',
          city: 'Viçosa do Ceará',
          neighborhood: 'Northeast',
          state: 'CE',
          country: 'Brasil',
          lat: -3.561013,
          lon: -41.090133,
        },
        distance: 0,
      },
    ];

    const response = getGreaterDistance(listDistance);
    expect(response).toEqual({
      origin: {
        place_name: 'A',
        street: 'Av. Rio Branco',
        housenumber: 1,
        postcode: '20090003',
        city: 'Rio de Janeiro',
        neighborhood: 'Centro',
        state: 'RJ',
        country: 'Brasil',
        lat: -22.89750765,
        lon: -43.18020490826943,
      },
      destiny: {
        place_name: 'C',
        street: 'Rua Horacio Fontenele Magalhaes',
        housenumber: 'SN',
        postcode: '62300-000',
        city: 'Viçosa do Ceará',
        neighborhood: 'Northeast',
        state: 'CE',
        country: 'Brasil',
        lat: -3.561013,
        lon: -41.090133,
      },
      distance: 2764.052,
    });
  });
});
